# ========= Development ========= # 
run:
	go run ./cmd/web start

compose-build:
	docker compose -p findthesniper build web

compose-up:
	docker compose -p findthesniper up --build web

compose-run:
	docker compose -p findthesniper up web

compose-down:
	docker compose -p findthesniper down
